fail_fast: true

repos:
  - repo: local
    hooks:
      - id: dev.install
        name: install locked dev dependencies
        entry: make dev.install
        language: system
        pass_filenames: false
  - repo: local
    hooks:
      - id: lint
        name: run linter
        entry: make lint
        language: system
        pass_filenames: false
  - repo: local
    hooks:
      - id: test
        name: run tests
        entry: make test
        language: system
        pass_filenames: false

